sudo: false
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
matrix:
  allow_failures:
    - python: nightly
install:
    - pip install flake8
    - pip install tox-travis
    - pip install coveralls
before_script:
    if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then flake8 . ; fi
script:
    - tox
after_success:
    coveralls
