sudo: false
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install flake8
    - pip install tox
    - pip install coveralls
before_script:
    flake8 .
script:
    - tox
after_success:
    coveralls
